/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Hero from "../../components/HomePage/Hero";
import PopularProducts from "../../components/HomePage/PopularProducts";
import NewProduct from "../../components/HomePage/NewProduct";
import Footer from "../../components/ProductPage/Footer";

const theme = createTheme({
  palette: {
    primary: {
      main: "#ed005d",
    },
    secondary: {
      main: "#000000",
    },
  },
  typography: {
    fontFamily: "Poppins, Arial, sans-serif",
  },
});

const MainLayout = () => {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Hero />
      <PopularProducts />
      <NewProduct />
      <Footer />
    </ThemeProvider>
  );
};

export default MainLayout;
