/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "../Button/Button";
import styles from "./Header.module.css";

const Header = () => {
  const navItems = ["Home", "All Colours", "Products", "About", "Contact"];

  return (
    <header className={styles.header}>
      <div className={styles.container}>
        <div className={styles.logoNav}>
          <div className={styles.logo}>Logo</div>
          <nav className={styles.nav}>
            {navItems.map((item, index) => (
              <a key={index} href="#" className={styles.navItem}>
                {item}
              </a>
            ))}
          </nav>
        </div>
        <div className={styles.actions}>
          <div className={styles.icons}>
            <img src="http://b.io/ext_25-" alt="" className={styles.icon} />
            <img src="http://b.io/ext_26-" alt="" className={styles.icon} />
            <img src="http://b.io/ext_27-" alt="" className={styles.icon} />
          </div>
          <div className={styles.buttons}>
            <Button variant="outline">Log in</Button>
            <Button variant="primary">Sign up</Button>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
