/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Button = ({ children, variant }) => {
  const baseClasses = "px-5 py-2 rounded-lg border border-solid";
  const variantClasses = {
    outline: "border-neutral-900 text-neutral-900",
    primary: "bg-rose-600 border-rose-600 text-white",
  };

  return (
    <button className={`${baseClasses} ${variantClasses[variant]}`}>
      {children}
    </button>
  );
};

export default Button;
