/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="flex flex-col justify-end self-stretch pt-20 pb-6 mt-28 w-full bg-black max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 justify-center items-start self-center px-5 w-full max-w-[1167px] max-md:flex-wrap max-md:max-w-full">
        <div className="flex flex-col py-0.5 text-base leading-6 text-neutral-50">
          <div className="text-2xl font-bold tracking-wider leading-6 max-md:mr-1">
            Exclusive
          </div>
          <div className="mt-7 text-xl font-medium leading-7">Subscribe</div>
          <div className="mt-6">Get 10% off your first order</div>
          <form className="flex gap-5 justify-between px-4 py-3 mt-4 rounded border-2 border-solid border-neutral-50">
            <label htmlFor="email" className="sr-only">
              Enter your email
            </label>
            <input
              type="email"
              id="email"
              placeholder="Enter your email"
              className="bg-transparent text-neutral-50"
            />
            <button type="submit" aria-label="Subscribe">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bea2c24624aec83b7f465f3f7dd6459b56a1974408d3a52263051296213050?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
                alt=""
                className="shrink-0 w-6 aspect-square"
              />
            </button>
          </form>
        </div>
        <nav className="flex flex-col text-base leading-6 text-neutral-50">
          <h2 className="text-xl font-medium leading-7">Support</h2>
          <address className="mt-6 leading-6 not-italic">
            111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.
          </address>
          <a href="mailto:email@gmail.com" className="mt-4">
            email@gmail.com
          </a>
          <a href="tel:+8801588888999" className="mt-4 max-md:mr-2.5">
            +88015-88888-9999
          </a>
        </nav>
        <nav className="flex flex-col text-base leading-6 text-neutral-50">
          <h2 className="text-xl font-medium leading-7">Account</h2>
          <a href="#" className="mt-6">
            My Account
          </a>
          <a href="#" className="mt-4">
            Login / Register
          </a>
          <a href="#" className="mt-4">
            Cart
          </a>
          <a href="#" className="mt-4">
            Wishlist
          </a>
          <a href="#" className="mt-4">
            Shop
          </a>
        </nav>
        <nav className="flex flex-col text-base leading-6 text-neutral-50">
          <h2 className="text-xl font-medium leading-7">Quick Link</h2>
          <a href="#" className="mt-6">
            Privacy Policy
          </a>
          <a href="#" className="mt-4">
            Terms Of Use
          </a>
          <a href="#" className="mt-4">
            FAQ
          </a>
          <a href="#" className="mt-4">
            Contact
          </a>
        </nav>
        <div className="flex flex-col self-stretch">
          <h2 className="text-xl font-medium leading-7 text-neutral-50">
            Download App
          </h2>
          <p className="mt-6 text-xs font-medium leading-5 text-neutral-50">
            Save $3 with App New User Only
          </p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f32c944482e002396698ad8ca9abe96f9e86704974028c48e92572cd9ecebede?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
            alt="QR Code"
            className="self-center mt-4 aspect-[1.54] w-[195px]"
          />
          <div className="flex gap-5 justify-between pr-7 mt-6 max-md:pr-5">
            <a href="#" aria-label="Facebook">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/30ef1881c8ba382ad841b10dec22c4728e1ac56594cd8fd1b8fc54e4c0c91052?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
                alt=""
                className="shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/32bc072c9992afd95bf51809363f11adb3d7edfc07e8a9d6f5db690f830d5153?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
                alt=""
                className="shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0b67f52bb53b8c3b436cfc50867157e647c1cc5fa6f7cc373ba309b35f3d286?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
                alt=""
                className="shrink-0 w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="LinkedIn">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/017f03fd6271e23e94e189db8506f53ec67e53623ecac07e20b0cc0e64aa481c?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
                alt=""
                className="shrink-0 w-6 aspect-square"
              />
            </a>
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center px-16 pt-4 mt-9 w-full text-base leading-6 text-white max-md:px-5 max-md:max-w-full">
        <div className="flex gap-1.5">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d70f19c1c306c3665c7ae4bbbdffeb0f7488c74899383a76a87a0b52a9d09d2?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
            alt=""
            className="shrink-0 my-auto w-5 aspect-square"
          />
          <p>Copyright Paints 2024. All right reserved</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
