/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

const Header = () => {
  const navItems = ["Home", "All Colours", "Products", "About", "Contact"];

  return (
    <header className="flex justify-center items-center self-stretch px-16 py-8 w-full border-b border-black max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 justify-center w-full max-w-[1170px] max-md:flex-wrap max-md:max-w-full">
        <div className="flex gap-5 my-auto text-black max-md:flex-wrap">
          <div className="grow text-2xl font-bold tracking-wider leading-6">
            Logo
          </div>
          <nav className="flex flex-auto gap-5 justify-between self-start text-base leading-6 text-center max-md:flex-wrap">
            {navItems.map((item, index) => (
              <a
                key={index}
                href="#"
                className={
                  index === 0 ? "whitespace-nowrap" : "py-1.5 whitespace-nowrap"
                }
              >
                {item}
              </a>
            ))}
          </nav>
        </div>
        <div className="flex gap-5">
          <div className="flex gap-4 justify-center my-auto">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a36546edd30f9649053810fdbf6c98d92541e863e7b8b10ab13af855343b34e?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
              alt=""
              className="shrink-0 my-auto w-6 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/850597cc14d3bfef027aa097fc5bca3ac1b650d683dc1d3c8c0134d5cd9a061d?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
              alt=""
              className="shrink-0 w-8 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ba6fc66b43efed62b99ccb8a18cb8c20c7f0c49b64ed7f3f9e76e7c63b52bcff?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
              alt=""
              className="shrink-0 w-8 aspect-square"
            />
          </div>
          <div className="flex gap-5 text-base text-center">
            <Button variant="outline">Log in</Button>
            <Button variant="primary">Sign up</Button>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
