/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProductCard = ({
  image,
  discount,
  title,
  price,
  originalPrice,
  rating,
}) => {
  return (
    <div className="flex flex-col grow text-base font-medium leading-6 max-md:mt-8">
      <div className="flex flex-col pt-3 w-full text-xs rounded bg-neutral-100">
        <div className="flex px-0.5 whitespace-nowrap text-neutral-50">
          <div className="flex flex-col">
            {discount && (
              <div className="px-3 py-1 bg-rose-600 rounded">{discount}</div>
            )}
            <img
              loading="lazy"
              src={image}
              alt={title}
              className="self-end max-w-full aspect-[1.39] w-[178px]"
            />
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2d9345dad452b03692cdbc613f709d144e723e1bbf5357d91182186f1925be37?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
            alt=""
            className="shrink-0 self-start aspect-square w-[34px]"
          />
        </div>
        <button className="flex justify-center items-center px-16 py-2.5 mt-10 w-full text-white bg-black rounded-none max-md:px-5">
          <div className="flex gap-2">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e462325802d0556992aa0397efea5256f6fd0a6001162dca8b6d920936baee1?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
              alt=""
              className="shrink-0 w-6 aspect-square"
            />
            <div className="my-auto">Add To Cart</div>
          </div>
        </button>
      </div>
      <div className="mt-4 text-black">{title}</div>
      <div className="flex gap-3 mt-2 whitespace-nowrap">
        <div className="text-red-500">${price}</div>
        {originalPrice && <div className="text-black">${originalPrice}</div>}
      </div>
      {rating && (
        <div className="flex gap-2 mt-2 text-sm font-semibold text-black whitespace-nowrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f79bd71a6471f38d5d1fc5e45c151fa99346fc4a5342fd2b25d87f1e68ade395?apiKey=4b22a28b78d84e32b8887416276aba72&&apiKey=4b22a28b78d84e32b8887416276aba72"
            alt="Rating"
            className="shrink-0 max-w-full aspect-[5] w-[100px]"
          />
          <div>({rating})</div>
        </div>
      )}
    </div>
  );
};

export default ProductCard;
