/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

const ProductGrid = ({ products }) => {
  return (
    <div className="flex gap-5 max-md:flex-col">
      {products.map((product, index) => (
        <div
          key={index}
          className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
        >
          <ProductCard {...product} />
        </div>
      ))}
    </div>
  );
};

export default ProductGrid;
