/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

const WishlistHeader = () => {
  return (
    <div className="flex gap-5 justify-between px-5 mt-16 w-full max-w-[1170px] max-md:flex-wrap max-md:mt-10 max-md:max-w-full">
      <div className="my-auto text-xl leading-7 text-center text-black">
        Wishlist (4)
      </div>
      <Button variant="outline">Move All To Bag</Button>
    </div>
  );
};

export default WishlistHeader;
