/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <div className={styles.container}>
        <div className={styles.column}>
          <h2 className={styles.logo}>Exclusive</h2>
          <h3 className={styles.subtitle}>Subscribe</h3>
          <p className={styles.text}>Get 10% off your first order</p>
          <form className={styles.subscribeForm}>
            <label htmlFor="email" className={styles.srOnly}>
              Enter your email
            </label>
            <input
              type="email"
              id="email"
              placeholder="Enter your email"
              className={styles.emailInput}
            />
            <button
              type="submit"
              aria-label="Subscribe"
              className={styles.submitButton}
            >
              <img
                src="http://b.io/ext_31-"
                alt=""
                className={styles.submitIcon}
              />
            </button>
          </form>
        </div>
        <nav className={styles.column}>
          <h2 className={styles.columnTitle}>Support</h2>
          <address className={styles.address}>
            111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.
          </address>
          <a href="mailto:email@gmail.com" className={styles.link}>
            email@gmail.com
          </a>
          <a href="tel:+8801588888999" className={styles.link}>
            +88015-88888-9999
          </a>
        </nav>
        <nav className={styles.column}>
          <h2 className={styles.columnTitle}>Account</h2>
          <a href="#" className={styles.link}>
            My Account
          </a>
          <a href="#" className={styles.link}>
            Login / Register
          </a>
          <a href="#" className={styles.link}>
            Cart
          </a>
          <a href="#" className={styles.link}>
            Wishlist
          </a>
          <a href="#" className={styles.link}>
            Shop
          </a>
        </nav>
        <nav className={styles.column}>
          <h2 className={styles.columnTitle}>Quick Link</h2>
          <a href="#" className={styles.link}>
            Privacy Policy
          </a>
          <a href="#" className={styles.link}>
            Terms Of Use
          </a>
          <a href="#" className={styles.link}>
            FAQ
          </a>
          <a href="#" className={styles.link}>
            Contact
          </a>
        </nav>
        <div className={styles.column}>
          <h2 className={styles.columnTitle}>Download App</h2>
          <p className={styles.appText}>Save $3 with App New User Only</p>
          <img
            src="http://b.io/ext_32-"
            alt="QR Code"
            className={styles.qrCode}
          />
          <div className={styles.socialLinks}>
            <a href="#" aria-label="Facebook">
              <img
                src="http://b.io/ext_33-"
                alt=""
                className={styles.socialIcon}
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                src="http://b.io/ext_34-"
                alt=""
                className={styles.socialIcon}
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                src="http://b.io/ext_35-"
                alt=""
                className={styles.socialIcon}
              />
            </a>
            <a href="#" aria-label="LinkedIn">
              <img
                src="http://b.io/ext_36-"
                alt=""
                className={styles.socialIcon}
              />
            </a>
          </div>
        </div>
      </div>
      <div className={styles.copyright}>
        <img
          src="http://b.io/ext_37-"
          alt=""
          className={styles.copyrightIcon}
        />
        <p>Copyright Paints 2024. All right reserved</p>
      </div>
    </footer>
  );
};

export default Footer;
